/* Generated by Pyrex 0.9.8.5 on Thu Jul 22 00:16:25 2010 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "corosync/corotypes.h"
#include "stdint.h"
#include "stdlib.h"
#include "sys/uio.h"
#include "string.h"
#include "corosync/cpg.h"


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static void __Pyx_WriteUnraisable(char *name); /*proto*/

static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from corosync.corotypes */


/* Declarations from corosync.libcpg */


/* Declarations from implementation of corosync.libcpg */

struct __pyx_obj_8corosync_6libcpg_CPG {
  PyObject_HEAD
  cpg_handle_t handle;
  cpg_guarantee_t guarantee;
  struct cpg_name group_name;
  PyObject *queue_in;
  PyObject *queue_ch;
};


static PyTypeObject *__pyx_ptype_8corosync_6libcpg_CPG = 0;
static void __pyx_f_8corosync_6libcpg_deliver_fn(cpg_handle_t,struct cpg_name *,uint32_t,uint32_t,void *,size_t); /*proto*/
static void __pyx_f_8corosync_6libcpg_confchg_fn(cpg_handle_t,struct cpg_name *,struct cpg_address *,size_t,struct cpg_address *,size_t,struct cpg_address *,size_t); /*proto*/

static char __pyx_k1[] = "queue_in";
static char __pyx_k2[] = "put";
static char __pyx_k3[] = "group_name";
static char __pyx_k4[] = "value";
static char __pyx_k5[] = "length";
static char __pyx_k6[] = "nodeid";
static char __pyx_k7[] = "pid";
static char __pyx_k8[] = "msg";
static char __pyx_k9[] = "msg_len";
static char __pyx_k10[] = "reason";
static char __pyx_k11[] = "queue_ch";
static char __pyx_k12[] = "member_list";
static char __pyx_k13[] = "member_list_entries";
static char __pyx_k14[] = "left_list";
static char __pyx_k15[] = "left_list_entries";
static char __pyx_k16[] = "joined_list";
static char __pyx_k17[] = "joined_list_entries";
static char __pyx_k18[] = "leave";
static char __pyx_k19[] = "sleep";
static char __pyx_k20[] = "finalize";
static char __pyx_k21[] = "Queue";
static char __pyx_k22[] = "initialization failed errcode=%i";
static char __pyx_k23[] = "did not finalized... errcode=%i";
static char __pyx_k24[] = "did not received FD... errcode=%i";
static char __pyx_k25[] = "Context get not implemented";
static char __pyx_k26[] = "Context set not implemented";
static char __pyx_k27[] = "dispatching failed reason code %i";
static char __pyx_k28[] = "join to group %s failed reason code %i";
static char __pyx_k29[] = "problems leaving group %s, reason code %i";
static char __pyx_k30[] = "message send faild...";
static char __pyx_k31[] = "did no received membership info reason code %i";
static char __pyx_k32[] = "local_node_id %i";
static char __pyx_k33[] = "Local get failed reason code %i";
static char __pyx_k34[] = "Flow control not implemented yet...";
static char __pyx_k35[] = "Zero copy buffer not used currently";
static char __pyx_k36[] = "iteration_initialize not used currently";
static char __pyx_k37[] = "iteration_next not used currently";
static char __pyx_k38[] = "iteration_finalize not used currently";
static char __pyx_k39[] = "time";

static PyObject *__pyx_n_Queue;
static PyObject *__pyx_n_finalize;
static PyObject *__pyx_n_group_name;
static PyObject *__pyx_n_joined_list;
static PyObject *__pyx_n_joined_list_entries;
static PyObject *__pyx_n_leave;
static PyObject *__pyx_n_left_list;
static PyObject *__pyx_n_left_list_entries;
static PyObject *__pyx_n_length;
static PyObject *__pyx_n_member_list;
static PyObject *__pyx_n_member_list_entries;
static PyObject *__pyx_n_msg;
static PyObject *__pyx_n_msg_len;
static PyObject *__pyx_n_nodeid;
static PyObject *__pyx_n_pid;
static PyObject *__pyx_n_put;
static PyObject *__pyx_n_queue_ch;
static PyObject *__pyx_n_queue_in;
static PyObject *__pyx_n_reason;
static PyObject *__pyx_n_sleep;
static PyObject *__pyx_n_time;
static PyObject *__pyx_n_value;

static PyObject *__pyx_k22p;
static PyObject *__pyx_k23p;
static PyObject *__pyx_k24p;
static PyObject *__pyx_k25p;
static PyObject *__pyx_k26p;
static PyObject *__pyx_k27p;
static PyObject *__pyx_k28p;
static PyObject *__pyx_k29p;
static PyObject *__pyx_k30p;
static PyObject *__pyx_k31p;
static PyObject *__pyx_k32p;
static PyObject *__pyx_k33p;
static PyObject *__pyx_k34p;
static PyObject *__pyx_k35p;
static PyObject *__pyx_k36p;
static PyObject *__pyx_k37p;
static PyObject *__pyx_k38p;

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_Queue, 1, __pyx_k21, sizeof(__pyx_k21)},
  {&__pyx_n_finalize, 1, __pyx_k20, sizeof(__pyx_k20)},
  {&__pyx_n_group_name, 1, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_n_joined_list, 1, __pyx_k16, sizeof(__pyx_k16)},
  {&__pyx_n_joined_list_entries, 1, __pyx_k17, sizeof(__pyx_k17)},
  {&__pyx_n_leave, 1, __pyx_k18, sizeof(__pyx_k18)},
  {&__pyx_n_left_list, 1, __pyx_k14, sizeof(__pyx_k14)},
  {&__pyx_n_left_list_entries, 1, __pyx_k15, sizeof(__pyx_k15)},
  {&__pyx_n_length, 1, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_n_member_list, 1, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_n_member_list_entries, 1, __pyx_k13, sizeof(__pyx_k13)},
  {&__pyx_n_msg, 1, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_n_msg_len, 1, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_n_nodeid, 1, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_n_pid, 1, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_n_put, 1, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_n_queue_ch, 1, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_n_queue_in, 1, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_n_reason, 1, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_n_sleep, 1, __pyx_k19, sizeof(__pyx_k19)},
  {&__pyx_n_time, 1, __pyx_k39, sizeof(__pyx_k39)},
  {&__pyx_n_value, 1, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_k22p, 0, __pyx_k22, sizeof(__pyx_k22)},
  {&__pyx_k23p, 0, __pyx_k23, sizeof(__pyx_k23)},
  {&__pyx_k24p, 0, __pyx_k24, sizeof(__pyx_k24)},
  {&__pyx_k25p, 0, __pyx_k25, sizeof(__pyx_k25)},
  {&__pyx_k26p, 0, __pyx_k26, sizeof(__pyx_k26)},
  {&__pyx_k27p, 0, __pyx_k27, sizeof(__pyx_k27)},
  {&__pyx_k28p, 0, __pyx_k28, sizeof(__pyx_k28)},
  {&__pyx_k29p, 0, __pyx_k29, sizeof(__pyx_k29)},
  {&__pyx_k30p, 0, __pyx_k30, sizeof(__pyx_k30)},
  {&__pyx_k31p, 0, __pyx_k31, sizeof(__pyx_k31)},
  {&__pyx_k32p, 0, __pyx_k32, sizeof(__pyx_k32)},
  {&__pyx_k33p, 0, __pyx_k33, sizeof(__pyx_k33)},
  {&__pyx_k34p, 0, __pyx_k34, sizeof(__pyx_k34)},
  {&__pyx_k35p, 0, __pyx_k35, sizeof(__pyx_k35)},
  {&__pyx_k36p, 0, __pyx_k36, sizeof(__pyx_k36)},
  {&__pyx_k37p, 0, __pyx_k37, sizeof(__pyx_k37)},
  {&__pyx_k38p, 0, __pyx_k38, sizeof(__pyx_k38)},
  {0, 0, 0, 0}
};



/* Implementation of corosync.libcpg */

static void __pyx_f_8corosync_6libcpg_deliver_fn(cpg_handle_t __pyx_v_handle,struct cpg_name *__pyx_v_group_name,uint32_t __pyx_v_nodeid,uint32_t __pyx_v_pid,void *__pyx_v_msg,size_t __pyx_v_msg_len) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_queue_in); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_put); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  __pyx_3 = PyDict_New(); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  __pyx_4 = PyString_FromString(__pyx_v_group_name->value); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_3, __pyx_n_value, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_4 = PyLong_FromUnsignedLong(__pyx_v_group_name->length); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_3, __pyx_n_length, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  if (PyDict_SetItem(__pyx_1, __pyx_n_group_name, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_4 = PyLong_FromUnsignedLong(__pyx_v_nodeid); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 14; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_nodeid, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_3 = PyLong_FromUnsignedLong(__pyx_v_pid); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 15; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_pid, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_4 = PyString_FromString(((char *)__pyx_v_msg)); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 16; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_msg, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_3 = PyInt_FromLong(__pyx_v_msg_len); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 17; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_msg_len, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_WriteUnraisable("corosync.libcpg.deliver_fn");
  __pyx_L0:;
}

static void __pyx_f_8corosync_6libcpg_confchg_fn(cpg_handle_t __pyx_v_handle,struct cpg_name *__pyx_v_group_name,struct cpg_address *__pyx_v_member_list,size_t __pyx_v_member_list_entries,struct cpg_address *__pyx_v_left_list,size_t __pyx_v_left_list_entries,struct cpg_address *__pyx_v_joined_list,size_t __pyx_v_joined_list_entries) {
  PyObject *__pyx_v_member_list_dict;
  PyObject *__pyx_v_idx;
  PyObject *__pyx_v_left_list_dict;
  PyObject *__pyx_v_joined_list_dict;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  Py_ssize_t __pyx_3;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  __pyx_v_member_list_dict = Py_None; Py_INCREF(Py_None);
  __pyx_v_idx = Py_None; Py_INCREF(Py_None);
  __pyx_v_left_list_dict = Py_None; Py_INCREF(Py_None);
  __pyx_v_joined_list_dict = Py_None; Py_INCREF(Py_None);

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":27 */
  __pyx_1 = PyObject_CallObject(((PyObject *)(&PyDict_Type)), 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; goto __pyx_L1;}
  Py_DECREF(__pyx_v_member_list_dict);
  __pyx_v_member_list_dict = __pyx_1;
  __pyx_1 = 0;

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":28 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
  Py_DECREF(__pyx_v_idx);
  __pyx_v_idx = __pyx_1;
  __pyx_1 = 0;

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":29 */
  while (1) {
    __pyx_1 = PyInt_FromLong(__pyx_v_member_list_entries); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
    if (PyObject_Cmp(__pyx_v_idx, __pyx_1, &__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
    __pyx_2 = __pyx_2 < 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    if (!__pyx_2) break;

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":30 */
    __pyx_1 = PyObject_CallObject(((PyObject *)(&PyDict_Type)), 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    if (PyObject_SetItem(__pyx_v_member_list_dict, __pyx_v_idx, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":31 */
    __pyx_3 = PyInt_AsSsize_t(__pyx_v_idx); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
    __pyx_1 = PyLong_FromUnsignedLong((__pyx_v_member_list[__pyx_3]).nodeid); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
    __pyx_4 = PyObject_GetItem(__pyx_v_member_list_dict, __pyx_v_idx); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
    if (PyObject_SetItem(__pyx_4, __pyx_n_nodeid, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":32 */
    __pyx_3 = PyInt_AsSsize_t(__pyx_v_idx); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    __pyx_1 = PyLong_FromUnsignedLong((__pyx_v_member_list[__pyx_3]).pid); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    __pyx_4 = PyObject_GetItem(__pyx_v_member_list_dict, __pyx_v_idx); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    if (PyObject_SetItem(__pyx_4, __pyx_n_pid, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":33 */
    __pyx_3 = PyInt_AsSsize_t(__pyx_v_idx); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
    __pyx_1 = PyLong_FromUnsignedLong((__pyx_v_member_list[__pyx_3]).reason); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
    __pyx_4 = PyObject_GetItem(__pyx_v_member_list_dict, __pyx_v_idx); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
    if (PyObject_SetItem(__pyx_4, __pyx_n_reason, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":34 */
    __pyx_1 = PyInt_FromLong(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}
    __pyx_4 = PyNumber_Add(__pyx_v_idx, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_v_idx);
    __pyx_v_idx = __pyx_4;
    __pyx_4 = 0;
  }

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":36 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; goto __pyx_L1;}
  Py_DECREF(__pyx_v_idx);
  __pyx_v_idx = __pyx_1;
  __pyx_1 = 0;

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":37 */
  __pyx_4 = PyObject_CallObject(((PyObject *)(&PyDict_Type)), 0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
  Py_DECREF(__pyx_v_left_list_dict);
  __pyx_v_left_list_dict = __pyx_4;
  __pyx_4 = 0;

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":38 */
  while (1) {
    __pyx_1 = PyInt_FromLong(__pyx_v_left_list_entries); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
    if (PyObject_Cmp(__pyx_v_idx, __pyx_1, &__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; goto __pyx_L1;}
    __pyx_2 = __pyx_2 < 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    if (!__pyx_2) break;

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":39 */
    __pyx_4 = PyObject_CallObject(((PyObject *)(&PyDict_Type)), 0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
    if (PyObject_SetItem(__pyx_v_left_list_dict, __pyx_v_idx, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":40 */
    __pyx_3 = PyInt_AsSsize_t(__pyx_v_idx); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
    __pyx_1 = PyLong_FromUnsignedLong((__pyx_v_left_list[__pyx_3]).nodeid); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
    __pyx_4 = PyObject_GetItem(__pyx_v_left_list_dict, __pyx_v_idx); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
    if (PyObject_SetItem(__pyx_4, __pyx_n_nodeid, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":41 */
    __pyx_3 = PyInt_AsSsize_t(__pyx_v_idx); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
    __pyx_1 = PyLong_FromUnsignedLong((__pyx_v_left_list[__pyx_3]).pid); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
    __pyx_4 = PyObject_GetItem(__pyx_v_left_list_dict, __pyx_v_idx); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
    if (PyObject_SetItem(__pyx_4, __pyx_n_pid, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":42 */
    __pyx_3 = PyInt_AsSsize_t(__pyx_v_idx); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; goto __pyx_L1;}
    __pyx_1 = PyLong_FromUnsignedLong((__pyx_v_left_list[__pyx_3]).reason); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; goto __pyx_L1;}
    __pyx_4 = PyObject_GetItem(__pyx_v_left_list_dict, __pyx_v_idx); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; goto __pyx_L1;}
    if (PyObject_SetItem(__pyx_4, __pyx_n_reason, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":43 */
    __pyx_1 = PyInt_FromLong(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
    __pyx_4 = PyNumber_Add(__pyx_v_idx, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_v_idx);
    __pyx_v_idx = __pyx_4;
    __pyx_4 = 0;
  }

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":45 */
  __pyx_1 = PyInt_FromLong(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
  Py_DECREF(__pyx_v_idx);
  __pyx_v_idx = __pyx_1;
  __pyx_1 = 0;

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":46 */
  __pyx_4 = PyObject_CallObject(((PyObject *)(&PyDict_Type)), 0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  Py_DECREF(__pyx_v_joined_list_dict);
  __pyx_v_joined_list_dict = __pyx_4;
  __pyx_4 = 0;

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":47 */
  while (1) {
    __pyx_1 = PyInt_FromLong(__pyx_v_joined_list_entries); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
    if (PyObject_Cmp(__pyx_v_idx, __pyx_1, &__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
    __pyx_2 = __pyx_2 < 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    if (!__pyx_2) break;

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":48 */
    __pyx_4 = PyObject_CallObject(((PyObject *)(&PyDict_Type)), 0); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
    if (PyObject_SetItem(__pyx_v_joined_list_dict, __pyx_v_idx, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":49 */
    __pyx_3 = PyInt_AsSsize_t(__pyx_v_idx); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
    __pyx_1 = PyLong_FromUnsignedLong((__pyx_v_joined_list[__pyx_3]).nodeid); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
    __pyx_4 = PyObject_GetItem(__pyx_v_joined_list_dict, __pyx_v_idx); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
    if (PyObject_SetItem(__pyx_4, __pyx_n_nodeid, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 49; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":50 */
    __pyx_3 = PyInt_AsSsize_t(__pyx_v_idx); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
    __pyx_1 = PyLong_FromUnsignedLong((__pyx_v_joined_list[__pyx_3]).pid); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
    __pyx_4 = PyObject_GetItem(__pyx_v_joined_list_dict, __pyx_v_idx); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
    if (PyObject_SetItem(__pyx_4, __pyx_n_pid, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":51 */
    __pyx_3 = PyInt_AsSsize_t(__pyx_v_idx); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}
    __pyx_1 = PyLong_FromUnsignedLong((__pyx_v_joined_list[__pyx_3]).reason); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}
    __pyx_4 = PyObject_GetItem(__pyx_v_joined_list_dict, __pyx_v_idx); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}
    if (PyObject_SetItem(__pyx_4, __pyx_n_reason, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":52 */
    __pyx_1 = PyInt_FromLong(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
    __pyx_4 = PyNumber_Add(__pyx_v_idx, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_v_idx);
    __pyx_v_idx = __pyx_4;
    __pyx_4 = 0;
  }

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":54 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_queue_ch); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  __pyx_4 = PyObject_GetAttr(__pyx_1, __pyx_n_put); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  __pyx_5 = PyDict_New(); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  __pyx_6 = PyString_FromString(__pyx_v_group_name->value); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_5, __pyx_n_value, __pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  __pyx_6 = PyLong_FromUnsignedLong(__pyx_v_group_name->length); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_5, __pyx_n_length, __pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  if (PyDict_SetItem(__pyx_1, __pyx_n_group_name, __pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  if (PyDict_SetItem(__pyx_1, __pyx_n_member_list, __pyx_v_member_list_dict) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  __pyx_6 = PyInt_FromLong(__pyx_v_member_list_entries); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_member_list_entries, __pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  if (PyDict_SetItem(__pyx_1, __pyx_n_left_list, __pyx_v_left_list_dict) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  __pyx_5 = PyInt_FromLong(__pyx_v_left_list_entries); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_left_list_entries, __pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  if (PyDict_SetItem(__pyx_1, __pyx_n_joined_list, __pyx_v_joined_list_dict) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  __pyx_6 = PyInt_FromLong(__pyx_v_joined_list_entries); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_joined_list_entries, __pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  __pyx_5 = PyTuple_New(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_6 = PyObject_CallObject(__pyx_4, __pyx_5); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(__pyx_6); __pyx_6 = 0;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  __Pyx_WriteUnraisable("corosync.libcpg.confchg_fn");
  __pyx_L0:;
  Py_DECREF(__pyx_v_member_list_dict);
  Py_DECREF(__pyx_v_idx);
  Py_DECREF(__pyx_v_left_list_dict);
  Py_DECREF(__pyx_v_joined_list_dict);
}

static int __pyx_f_8corosync_6libcpg_3CPG___cinit__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_8corosync_6libcpg_3CPG___cinit__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_name = 0;
  int __pyx_v_length;
  int __pyx_r;
  Py_ssize_t __pyx_1;
  char *__pyx_2;
  static char *__pyx_argnames[] = {"name",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_name)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_name);

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":75 */
  __pyx_1 = PyObject_Length(__pyx_v_name); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; goto __pyx_L1;}
  __pyx_v_length = __pyx_1;

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":76 */
  __pyx_2 = PyString_AsString(__pyx_v_name); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  __pyx_1 = PyObject_Length(__pyx_v_name); if (__pyx_1 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 76; goto __pyx_L1;}
  strncpy(((struct __pyx_obj_8corosync_6libcpg_CPG *)__pyx_v_self)->group_name.value,__pyx_2,__pyx_1);

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":77 */
  ((struct __pyx_obj_8corosync_6libcpg_CPG *)__pyx_v_self)->group_name.length = __pyx_v_length;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("corosync.libcpg.CPG.__cinit__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_name);
  return __pyx_r;
}

static void __pyx_f_8corosync_6libcpg_3CPG___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_8corosync_6libcpg_3CPG___dealloc__(PyObject *__pyx_v_self) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":81 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_leave); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":82 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_sleep); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":83 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_finalize); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
  __pyx_3 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("corosync.libcpg.CPG.__dealloc__");
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
}

static PyObject *__pyx_f_8corosync_6libcpg_3CPG_initialize(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_8corosync_6libcpg_3CPG_initialize(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  cpg_callbacks_t __pyx_v_callbacks;
  int __pyx_v_retval;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":91 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_Queue); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_queue_in, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":92 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_Queue); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_n_queue_ch, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":93 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_queue_in); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  Py_DECREF(((struct __pyx_obj_8corosync_6libcpg_CPG *)__pyx_v_self)->queue_in);
  ((struct __pyx_obj_8corosync_6libcpg_CPG *)__pyx_v_self)->queue_in = __pyx_1;
  __pyx_1 = 0;

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":94 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_queue_ch); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 94; goto __pyx_L1;}
  Py_DECREF(((struct __pyx_obj_8corosync_6libcpg_CPG *)__pyx_v_self)->queue_ch);
  ((struct __pyx_obj_8corosync_6libcpg_CPG *)__pyx_v_self)->queue_ch = __pyx_2;
  __pyx_2 = 0;

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":95 */
  __pyx_v_callbacks.cpg_deliver_fn = __pyx_f_8corosync_6libcpg_deliver_fn;

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":96 */
  __pyx_v_callbacks.cpg_confchg_fn = __pyx_f_8corosync_6libcpg_confchg_fn;

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":97 */
  __pyx_v_retval = cpg_initialize((&((struct __pyx_obj_8corosync_6libcpg_CPG *)__pyx_v_self)->handle),(&__pyx_v_callbacks));

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":98 */
  __pyx_3 = (__pyx_v_retval == CS_OK);
  if (__pyx_3) {
    Py_INCREF(Py_True);
    __pyx_r = Py_True;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":101 */
    __pyx_1 = PyInt_FromLong(__pyx_v_retval); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
    __pyx_2 = PyNumber_Remainder(__pyx_k22p, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    if (__Pyx_PrintItem(__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":102 */
    Py_INCREF(Py_False);
    __pyx_r = Py_False;
    goto __pyx_L0;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("corosync.libcpg.CPG.initialize");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_8corosync_6libcpg_3CPG_finalize(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_8corosync_6libcpg_3CPG_finalize(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_retval;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":106 */
  __pyx_v_retval = cpg_finalize(((struct __pyx_obj_8corosync_6libcpg_CPG *)__pyx_v_self)->handle);

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":107 */
  __pyx_1 = (__pyx_v_retval == CS_OK);
  if (__pyx_1) {
    Py_INCREF(Py_True);
    __pyx_r = Py_True;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":111 */
    __pyx_2 = PyInt_FromLong(__pyx_v_retval); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
    __pyx_3 = PyNumber_Remainder(__pyx_k23p, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (__Pyx_PrintItem(__pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":112 */
    Py_INCREF(Py_False);
    __pyx_r = Py_False;
    goto __pyx_L0;
  }
  __pyx_L2:;

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":114 */

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("corosync.libcpg.CPG.finalize");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_8corosync_6libcpg_3CPG_fd_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_8corosync_6libcpg_3CPG_fd_get[] = " TODO ";
static PyObject *__pyx_f_8corosync_6libcpg_3CPG_fd_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_fd_val;
  int __pyx_v_retval;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":120 */
  __pyx_v_retval = cpg_fd_get(((struct __pyx_obj_8corosync_6libcpg_CPG *)__pyx_v_self)->handle,(&__pyx_v_fd_val));

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":121 */
  __pyx_1 = (__pyx_v_retval == CS_OK);
  if (__pyx_1) {
    __pyx_2 = PyInt_FromLong(__pyx_v_fd_val); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
    __pyx_r = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":124 */
    __pyx_2 = PyInt_FromLong(__pyx_v_retval); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
    __pyx_3 = PyNumber_Remainder(__pyx_k24p, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (__Pyx_PrintItem(__pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":125 */
    Py_INCREF(Py_None);
    __pyx_r = Py_None;
    goto __pyx_L0;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("corosync.libcpg.CPG.fd_get");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_8corosync_6libcpg_3CPG_context_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_8corosync_6libcpg_3CPG_context_get[] = " TODO ";
static PyObject *__pyx_f_8corosync_6libcpg_3CPG_context_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __Pyx_Raise(PyExc_NotImplementedError, __pyx_k25p, 0);
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("corosync.libcpg.CPG.context_get");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_8corosync_6libcpg_3CPG_context_set(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_8corosync_6libcpg_3CPG_context_set[] = " TODO ";
static PyObject *__pyx_f_8corosync_6libcpg_3CPG_context_set(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __Pyx_Raise(PyExc_NotImplementedError, __pyx_k26p, 0);
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("corosync.libcpg.CPG.context_set");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_8corosync_6libcpg_3CPG_dispatch(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_8corosync_6libcpg_3CPG_dispatch(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_dispatch_type = 0;
  cs_dispatch_flags_t __pyx_v_val;
  int __pyx_v_retval;
  PyObject *__pyx_r;
  cs_dispatch_flags_t __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"dispatch_type",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_dispatch_type)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_dispatch_type);

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":138 */
  __pyx_1 = ((cs_dispatch_flags_t)PyInt_AsLong(__pyx_v_dispatch_type)); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
  __pyx_v_val = __pyx_1;

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":139 */
  __pyx_v_retval = cpg_dispatch(((struct __pyx_obj_8corosync_6libcpg_CPG *)__pyx_v_self)->handle,__pyx_v_val);

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":140 */
  __pyx_2 = (__pyx_v_retval == CS_OK);
  if (__pyx_2) {
    Py_INCREF(Py_True);
    __pyx_r = Py_True;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":143 */
    __pyx_3 = PyInt_FromLong(__pyx_v_retval); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 143; goto __pyx_L1;}
    __pyx_4 = PyNumber_Remainder(__pyx_k27p, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 143; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    if (__Pyx_PrintItem(__pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 143; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 143; goto __pyx_L1;}

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":144 */
    Py_INCREF(Py_False);
    __pyx_r = Py_False;
    goto __pyx_L0;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("corosync.libcpg.CPG.dispatch");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_dispatch_type);
  return __pyx_r;
}

static PyObject *__pyx_f_8corosync_6libcpg_3CPG_join(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_8corosync_6libcpg_3CPG_join(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_retval;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":148 */
  __pyx_v_retval = cpg_join(((struct __pyx_obj_8corosync_6libcpg_CPG *)__pyx_v_self)->handle,(&((struct __pyx_obj_8corosync_6libcpg_CPG *)__pyx_v_self)->group_name));

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":149 */
  __pyx_1 = (__pyx_v_retval == CS_OK);
  if (__pyx_1) {
    Py_INCREF(Py_True);
    __pyx_r = Py_True;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":152 */
    __pyx_2 = PyString_FromString(((struct __pyx_obj_8corosync_6libcpg_CPG *)__pyx_v_self)->group_name.value); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(__pyx_v_retval); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
    PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
    __pyx_2 = 0;
    __pyx_3 = 0;
    __pyx_2 = PyNumber_Remainder(__pyx_k28p, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    if (__Pyx_PrintItem(__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 152; goto __pyx_L1;}

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":153 */
    Py_INCREF(Py_False);
    __pyx_r = Py_False;
    goto __pyx_L0;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("corosync.libcpg.CPG.join");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_8corosync_6libcpg_3CPG_leave(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_8corosync_6libcpg_3CPG_leave(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_retval;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":158 */
  __pyx_v_retval = cpg_leave(((struct __pyx_obj_8corosync_6libcpg_CPG *)__pyx_v_self)->handle,(&((struct __pyx_obj_8corosync_6libcpg_CPG *)__pyx_v_self)->group_name));

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":159 */
  __pyx_1 = (__pyx_v_retval == CS_OK);
  if (__pyx_1) {
    Py_INCREF(Py_True);
    __pyx_r = Py_True;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":162 */
    __pyx_2 = PyString_FromString(((struct __pyx_obj_8corosync_6libcpg_CPG *)__pyx_v_self)->group_name.value); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(__pyx_v_retval); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
    PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
    __pyx_2 = 0;
    __pyx_3 = 0;
    __pyx_2 = PyNumber_Remainder(__pyx_k29p, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    if (__Pyx_PrintItem(__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 162; goto __pyx_L1;}

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":163 */
    Py_INCREF(Py_True);
    __pyx_r = Py_True;
    goto __pyx_L0;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("corosync.libcpg.CPG.leave");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_8corosync_6libcpg_3CPG_mcast_joined(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_8corosync_6libcpg_3CPG_mcast_joined(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  char *__pyx_v_msg;
  PyObject *__pyx_v_p_guarantee = 0;
  cpg_guarantee_t __pyx_v_guarantee;
  struct iovec *__pyx_v_idata;
  int __pyx_v_retval;
  PyObject *__pyx_r;
  cpg_guarantee_t __pyx_1;
  PyObject *__pyx_2 = 0;
  Py_ssize_t __pyx_3;
  int __pyx_4;
  static char *__pyx_argnames[] = {"msg","p_guarantee",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "sO", __pyx_argnames, &__pyx_v_msg, &__pyx_v_p_guarantee)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_p_guarantee);

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":167 */
  __pyx_1 = ((cpg_guarantee_t)PyInt_AsLong(__pyx_v_p_guarantee)); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 167; goto __pyx_L1;}
  __pyx_v_guarantee = __pyx_1;

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":169 */
  __pyx_v_idata = ((struct iovec *)malloc((sizeof(struct iovec))));

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":170 */
  __pyx_v_idata->iov_base = __pyx_v_msg;

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":171 */
  __pyx_2 = PyString_FromString(__pyx_v_msg); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 171; goto __pyx_L1;}
  __pyx_3 = PyObject_Length(__pyx_2); if (__pyx_3 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 171; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_v_idata->iov_len = __pyx_3;

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":173 */
  __pyx_v_retval = cpg_mcast_joined(((struct __pyx_obj_8corosync_6libcpg_CPG *)__pyx_v_self)->handle,__pyx_v_guarantee,__pyx_v_idata,1);

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":174 */
  free(__pyx_v_idata);

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":175 */
  __pyx_4 = (__pyx_v_retval != CS_OK);
  if (__pyx_4) {
    if (__Pyx_PrintItem(__pyx_k30p) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 176; goto __pyx_L1;}
    if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 176; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("corosync.libcpg.CPG.mcast_joined");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_p_guarantee);
  return __pyx_r;
}

static PyObject *__pyx_f_8corosync_6libcpg_3CPG_membership_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_8corosync_6libcpg_3CPG_membership_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct cpg_address __pyx_v_member_list[64];
  int __pyx_v_member_list_entries;
  int __pyx_v_retval;
  PyObject *__pyx_v_member_list_dict;
  PyObject *__pyx_v_idx;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  Py_ssize_t __pyx_3;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_member_list_dict = Py_None; Py_INCREF(Py_None);
  __pyx_v_idx = Py_None; Py_INCREF(Py_None);

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":191 */
  __pyx_v_retval = cpg_membership_get(((struct __pyx_obj_8corosync_6libcpg_CPG *)__pyx_v_self)->handle,(&((struct __pyx_obj_8corosync_6libcpg_CPG *)__pyx_v_self)->group_name),__pyx_v_member_list,(&__pyx_v_member_list_entries));

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":195 */
  __pyx_1 = (__pyx_v_retval == CS_OK);
  if (__pyx_1) {

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":196 */
    __pyx_2 = PyObject_CallObject(((PyObject *)(&PyDict_Type)), 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 196; goto __pyx_L1;}
    Py_DECREF(__pyx_v_member_list_dict);
    __pyx_v_member_list_dict = __pyx_2;
    __pyx_2 = 0;

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":197 */
    __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 197; goto __pyx_L1;}
    Py_DECREF(__pyx_v_idx);
    __pyx_v_idx = __pyx_2;
    __pyx_2 = 0;

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":198 */
    while (1) {
      __pyx_2 = PyInt_FromLong(__pyx_v_member_list_entries); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 198; goto __pyx_L1;}
      if (PyObject_Cmp(__pyx_v_idx, __pyx_2, &__pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 198; goto __pyx_L1;}
      __pyx_1 = __pyx_1 < 0;
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      if (!__pyx_1) break;

      /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":199 */
      __pyx_2 = PyObject_CallObject(((PyObject *)(&PyDict_Type)), 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 199; goto __pyx_L1;}
      if (PyObject_SetItem(__pyx_v_member_list_dict, __pyx_v_idx, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 199; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;

      /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":200 */
      __pyx_3 = PyInt_AsSsize_t(__pyx_v_idx); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 200; goto __pyx_L1;}
      __pyx_2 = PyLong_FromUnsignedLong((__pyx_v_member_list[__pyx_3]).nodeid); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 200; goto __pyx_L1;}
      __pyx_4 = PyObject_GetItem(__pyx_v_member_list_dict, __pyx_v_idx); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 200; goto __pyx_L1;}
      if (PyObject_SetItem(__pyx_4, __pyx_n_nodeid, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 200; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      Py_DECREF(__pyx_2); __pyx_2 = 0;

      /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":201 */
      __pyx_3 = PyInt_AsSsize_t(__pyx_v_idx); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 201; goto __pyx_L1;}
      __pyx_2 = PyLong_FromUnsignedLong((__pyx_v_member_list[__pyx_3]).pid); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 201; goto __pyx_L1;}
      __pyx_4 = PyObject_GetItem(__pyx_v_member_list_dict, __pyx_v_idx); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 201; goto __pyx_L1;}
      if (PyObject_SetItem(__pyx_4, __pyx_n_pid, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 201; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      Py_DECREF(__pyx_2); __pyx_2 = 0;

      /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":202 */
      __pyx_3 = PyInt_AsSsize_t(__pyx_v_idx); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
      __pyx_2 = PyLong_FromUnsignedLong((__pyx_v_member_list[__pyx_3]).reason); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
      __pyx_4 = PyObject_GetItem(__pyx_v_member_list_dict, __pyx_v_idx); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
      if (PyObject_SetItem(__pyx_4, __pyx_n_reason, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 202; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      Py_DECREF(__pyx_2); __pyx_2 = 0;

      /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":203 */
      __pyx_2 = PyInt_FromLong(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 203; goto __pyx_L1;}
      __pyx_4 = PyNumber_Add(__pyx_v_idx, __pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 203; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_v_idx);
      __pyx_v_idx = __pyx_4;
      __pyx_4 = 0;
    }

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":204 */
    __pyx_2 = PyDict_New(); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 204; goto __pyx_L1;}
    if (PyDict_SetItem(__pyx_2, __pyx_n_member_list, __pyx_v_member_list_dict) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 204; goto __pyx_L1;}
    __pyx_r = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":206 */
    __pyx_4 = PyInt_FromLong(__pyx_v_retval); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 206; goto __pyx_L1;}
    __pyx_2 = PyNumber_Remainder(__pyx_k31p, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 206; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    if (__Pyx_PrintItem(__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 206; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 206; goto __pyx_L1;}

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":207 */
    Py_INCREF(Py_None);
    __pyx_r = Py_None;
    goto __pyx_L0;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("corosync.libcpg.CPG.membership_get");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_member_list_dict);
  Py_DECREF(__pyx_v_idx);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_8corosync_6libcpg_3CPG_local_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_8corosync_6libcpg_3CPG_local_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  unsigned int __pyx_v_local_nodeid;
  int __pyx_v_retval;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":213 */
  __pyx_v_retval = cpg_local_get(((struct __pyx_obj_8corosync_6libcpg_CPG *)__pyx_v_self)->handle,(&__pyx_v_local_nodeid));

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":215 */
  __pyx_1 = (__pyx_v_retval == CS_OK);
  if (__pyx_1) {

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":216 */
    __pyx_2 = PyLong_FromUnsignedLong(__pyx_v_local_nodeid); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}
    __pyx_3 = PyNumber_Remainder(__pyx_k32p, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (__Pyx_PrintItem(__pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 216; goto __pyx_L1;}

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":217 */
    __pyx_2 = PyLong_FromUnsignedLong(__pyx_v_local_nodeid); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 217; goto __pyx_L1;}
    __pyx_r = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":219 */
    __pyx_3 = PyInt_FromLong(__pyx_v_retval); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 219; goto __pyx_L1;}
    __pyx_2 = PyNumber_Remainder(__pyx_k33p, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 219; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    if (__Pyx_PrintItem(__pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 219; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    if (__Pyx_PrintNewline() < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 219; goto __pyx_L1;}

    /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":220 */
    Py_INCREF(Py_None);
    __pyx_r = Py_None;
    goto __pyx_L0;
  }
  __pyx_L2:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("corosync.libcpg.CPG.local_get");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_8corosync_6libcpg_3CPG_flow_control_state_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_8corosync_6libcpg_3CPG_flow_control_state_get[] = " TODO ";
static PyObject *__pyx_f_8corosync_6libcpg_3CPG_flow_control_state_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __Pyx_Raise(PyExc_NotImplementedError, __pyx_k34p, 0);
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 225; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("corosync.libcpg.CPG.flow_control_state_get");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_8corosync_6libcpg_3CPG_zcb_alloc(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_8corosync_6libcpg_3CPG_zcb_alloc[] = " TODO ";
static PyObject *__pyx_f_8corosync_6libcpg_3CPG_zcb_alloc(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __Pyx_Raise(PyExc_NotImplementedError, __pyx_k35p, 0);
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 229; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("corosync.libcpg.CPG.zcb_alloc");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_8corosync_6libcpg_3CPG_zcb_free(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_8corosync_6libcpg_3CPG_zcb_free[] = " TODO ";
static PyObject *__pyx_f_8corosync_6libcpg_3CPG_zcb_free(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __Pyx_Raise(PyExc_NotImplementedError, __pyx_k35p, 0);
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 233; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("corosync.libcpg.CPG.zcb_free");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_8corosync_6libcpg_3CPG_zcb_mcast_joined(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_8corosync_6libcpg_3CPG_zcb_mcast_joined[] = " TODO ";
static PyObject *__pyx_f_8corosync_6libcpg_3CPG_zcb_mcast_joined(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __Pyx_Raise(PyExc_NotImplementedError, __pyx_k35p, 0);
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 237; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("corosync.libcpg.CPG.zcb_mcast_joined");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_8corosync_6libcpg_3CPG_iteration_initialize(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_8corosync_6libcpg_3CPG_iteration_initialize[] = " TODO ";
static PyObject *__pyx_f_8corosync_6libcpg_3CPG_iteration_initialize(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __Pyx_Raise(PyExc_NotImplementedError, __pyx_k36p, 0);
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 241; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("corosync.libcpg.CPG.iteration_initialize");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_8corosync_6libcpg_3CPG_iteration_next(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_8corosync_6libcpg_3CPG_iteration_next[] = " TODO ";
static PyObject *__pyx_f_8corosync_6libcpg_3CPG_iteration_next(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __Pyx_Raise(PyExc_NotImplementedError, __pyx_k37p, 0);
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 245; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("corosync.libcpg.CPG.iteration_next");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_8corosync_6libcpg_3CPG_iteration_finalize(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_8corosync_6libcpg_3CPG_iteration_finalize[] = " TODO ";
static PyObject *__pyx_f_8corosync_6libcpg_3CPG_iteration_finalize(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_r;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __Pyx_Raise(PyExc_NotImplementedError, __pyx_k38p, 0);
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 249; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("corosync.libcpg.CPG.iteration_finalize");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_tp_new_8corosync_6libcpg_CPG(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_8corosync_6libcpg_CPG *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_8corosync_6libcpg_CPG *)o);
  p->queue_in = Py_None; Py_INCREF(Py_None);
  p->queue_ch = Py_None; Py_INCREF(Py_None);
  if (__pyx_f_8corosync_6libcpg_3CPG___cinit__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_8corosync_6libcpg_CPG(PyObject *o) {
  struct __pyx_obj_8corosync_6libcpg_CPG *p = (struct __pyx_obj_8corosync_6libcpg_CPG *)o;
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_8corosync_6libcpg_3CPG___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  Py_XDECREF(p->queue_in);
  Py_XDECREF(p->queue_ch);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_8corosync_6libcpg_CPG(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_8corosync_6libcpg_CPG *p = (struct __pyx_obj_8corosync_6libcpg_CPG *)o;
  if (p->queue_in) {
    e = (*v)(p->queue_in, a); if (e) return e;
  }
  if (p->queue_ch) {
    e = (*v)(p->queue_ch, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_8corosync_6libcpg_CPG(PyObject *o) {
  struct __pyx_obj_8corosync_6libcpg_CPG *p = (struct __pyx_obj_8corosync_6libcpg_CPG *)o;
  PyObject *t;
  t = p->queue_in; 
  p->queue_in = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(t);
  t = p->queue_ch; 
  p->queue_ch = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(t);
  return 0;
}

static struct PyMethodDef __pyx_methods_8corosync_6libcpg_CPG[] = {
  {"initialize", (PyCFunction)__pyx_f_8corosync_6libcpg_3CPG_initialize, METH_VARARGS|METH_KEYWORDS, 0},
  {"finalize", (PyCFunction)__pyx_f_8corosync_6libcpg_3CPG_finalize, METH_VARARGS|METH_KEYWORDS, 0},
  {"fd_get", (PyCFunction)__pyx_f_8corosync_6libcpg_3CPG_fd_get, METH_VARARGS|METH_KEYWORDS, __pyx_doc_8corosync_6libcpg_3CPG_fd_get},
  {"context_get", (PyCFunction)__pyx_f_8corosync_6libcpg_3CPG_context_get, METH_VARARGS|METH_KEYWORDS, __pyx_doc_8corosync_6libcpg_3CPG_context_get},
  {"context_set", (PyCFunction)__pyx_f_8corosync_6libcpg_3CPG_context_set, METH_VARARGS|METH_KEYWORDS, __pyx_doc_8corosync_6libcpg_3CPG_context_set},
  {"dispatch", (PyCFunction)__pyx_f_8corosync_6libcpg_3CPG_dispatch, METH_VARARGS|METH_KEYWORDS, 0},
  {"join", (PyCFunction)__pyx_f_8corosync_6libcpg_3CPG_join, METH_VARARGS|METH_KEYWORDS, 0},
  {"leave", (PyCFunction)__pyx_f_8corosync_6libcpg_3CPG_leave, METH_VARARGS|METH_KEYWORDS, 0},
  {"mcast_joined", (PyCFunction)__pyx_f_8corosync_6libcpg_3CPG_mcast_joined, METH_VARARGS|METH_KEYWORDS, 0},
  {"membership_get", (PyCFunction)__pyx_f_8corosync_6libcpg_3CPG_membership_get, METH_VARARGS|METH_KEYWORDS, 0},
  {"local_get", (PyCFunction)__pyx_f_8corosync_6libcpg_3CPG_local_get, METH_VARARGS|METH_KEYWORDS, 0},
  {"flow_control_state_get", (PyCFunction)__pyx_f_8corosync_6libcpg_3CPG_flow_control_state_get, METH_VARARGS|METH_KEYWORDS, __pyx_doc_8corosync_6libcpg_3CPG_flow_control_state_get},
  {"zcb_alloc", (PyCFunction)__pyx_f_8corosync_6libcpg_3CPG_zcb_alloc, METH_VARARGS|METH_KEYWORDS, __pyx_doc_8corosync_6libcpg_3CPG_zcb_alloc},
  {"zcb_free", (PyCFunction)__pyx_f_8corosync_6libcpg_3CPG_zcb_free, METH_VARARGS|METH_KEYWORDS, __pyx_doc_8corosync_6libcpg_3CPG_zcb_free},
  {"zcb_mcast_joined", (PyCFunction)__pyx_f_8corosync_6libcpg_3CPG_zcb_mcast_joined, METH_VARARGS|METH_KEYWORDS, __pyx_doc_8corosync_6libcpg_3CPG_zcb_mcast_joined},
  {"iteration_initialize", (PyCFunction)__pyx_f_8corosync_6libcpg_3CPG_iteration_initialize, METH_VARARGS|METH_KEYWORDS, __pyx_doc_8corosync_6libcpg_3CPG_iteration_initialize},
  {"iteration_next", (PyCFunction)__pyx_f_8corosync_6libcpg_3CPG_iteration_next, METH_VARARGS|METH_KEYWORDS, __pyx_doc_8corosync_6libcpg_3CPG_iteration_next},
  {"iteration_finalize", (PyCFunction)__pyx_f_8corosync_6libcpg_3CPG_iteration_finalize, METH_VARARGS|METH_KEYWORDS, __pyx_doc_8corosync_6libcpg_3CPG_iteration_finalize},
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_8corosync_6libcpg_CPG[] = {
  {"queue_in", T_OBJECT, offsetof(struct __pyx_obj_8corosync_6libcpg_CPG, queue_in), 0, 0},
  {"queue_ch", T_OBJECT, offsetof(struct __pyx_obj_8corosync_6libcpg_CPG, queue_ch), 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_CPG = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_CPG = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_CPG = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_CPG = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_8corosync_6libcpg_CPG = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "corosync.libcpg.CPG", /*tp_name*/
  sizeof(struct __pyx_obj_8corosync_6libcpg_CPG), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_8corosync_6libcpg_CPG, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_CPG, /*tp_as_number*/
  &__pyx_tp_as_sequence_CPG, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_CPG, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_CPG, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_8corosync_6libcpg_CPG, /*tp_traverse*/
  __pyx_tp_clear_8corosync_6libcpg_CPG, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_8corosync_6libcpg_CPG, /*tp_methods*/
  __pyx_members_8corosync_6libcpg_CPG, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_8corosync_6libcpg_CPG, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initlibcpg(void); /*proto*/
PyMODINIT_FUNC initlibcpg(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("libcpg", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_type_8corosync_6libcpg_CPG.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_8corosync_6libcpg_CPG) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "CPG", (PyObject *)&__pyx_type_8corosync_6libcpg_CPG) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; goto __pyx_L1;}
  __pyx_ptype_8corosync_6libcpg_CPG = &__pyx_type_8corosync_6libcpg_CPG;

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":1 */
  __pyx_1 = PyList_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  Py_INCREF(__pyx_n_sleep);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_n_sleep);
  __pyx_2 = __Pyx_Import(__pyx_n_time, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_sleep); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_sleep, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":2 */
  __pyx_2 = PyList_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;}
  Py_INCREF(__pyx_n_Queue);
  PyList_SET_ITEM(__pyx_2, 0, __pyx_n_Queue);
  __pyx_1 = __Pyx_Import(__pyx_n_Queue, __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_Queue); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_Queue, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":64 */
  if (PyObject_SetAttr(__pyx_m, __pyx_n_queue_in, Py_None) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; goto __pyx_L1;}

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":65 */
  if (PyObject_SetAttr(__pyx_m, __pyx_n_queue_ch, Py_None) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}

  /* "/home/steki/python-corosync/lib/corosync/libcpg.pyx":247 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("corosync.libcpg");
}

static char *__pyx_filenames[] = {
  "libcpg.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_WriteUnraisable(char *name) {
    PyObject *old_exc, *old_val, *old_tb;
    PyObject *ctx;
    PyErr_Fetch(&old_exc, &old_val, &old_tb);
    ctx = PyString_FromString(name);
    PyErr_Restore(old_exc, old_val, old_tb);
    if (!ctx)
        ctx = Py_None;
    PyErr_WriteUnraisable(ctx);
}

static PyObject *__Pyx_GetStdout(void) {
    PyObject *f = PySys_GetObject("stdout");
    if (!f) {
        PyErr_SetString(PyExc_RuntimeError, "lost sys.stdout");
    }
    return f;
}

static int __Pyx_PrintItem(PyObject *v) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_SoftSpace(f, 1)) {
        if (PyFile_WriteString(" ", f) < 0)
            return -1;
    }
    if (PyFile_WriteObject(v, f, Py_PRINT_RAW) < 0)
        return -1;
    if (PyString_Check(v)) {
        char *s = PyString_AsString(v);
        Py_ssize_t len = PyString_Size(v);
        if (len > 0 &&
            isspace(Py_CHARMASK(s[len-1])) &&
            s[len-1] != ' ')
                PyFile_SoftSpace(f, 0);
    }
    return 0;
}

static int __Pyx_PrintNewline(void) {
    PyObject *f;
    
    if (!(f = __Pyx_GetStdout()))
        return -1;
    if (PyFile_WriteString("\n", f) < 0)
        return -1;
    PyFile_SoftSpace(f, 0);
    return 0;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) type->ob_type;
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
